name: Docker Image CI

on:
  push:
   # branches: '**'
  pull_request:
   # branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'temurin'
        cache: maven
    - name: Build a package
      run: mvn -B package --file pom.xml; docker build . --tag infodisplay:$(date +%s) --build-arg WORKSPACE=${{ github.workspace }}/target/InfoDisplay.jar; docker push joschi87.net:9000/infodisplay:$(date +%s)

